profiles:
  production:
    base_url: http://goldmann.pl/
    deploy:
      host: goldmann.pl
      path: /var/www/goldmann.pl/htdocs/
intense_debate_acct: dc0fe4e524f2a8f99420088ae1c04124
google_analytics: UA-351971-1
